### ISSUE TITLE
Add snyk security check on travis build

### ISSUE THREAD

**Issue by j1348** [j1348/timelapse-api#6]

**Comment by thakkaryash94** [comment]
I can do this, but to successfully integrate, we need to sign up on snyk and add API Token in travis in environment Variables as "SNYK_TOKEN" as written in this [blog](https://blog.travis-ci.com/2017-04-20-continuous-security-snyk-travis-ci/).

One more thing, as we are using mongoose for db, our test case will also fail and travis will show error like below.

```sh
> timelapse-api@0.1.1 test /home/travis/build/thakkaryash94/timelapse-api
> NODE_ENV=test ./node_modules/.bin/lab -l
(node:3032) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client
Database connection is lost
Database connection has an error: MongoError: failed to connect to server [undefined:27017] on first connect [MongoError: getaddrinfo ENOTFOUND undefined undefined:27017]
  
  ..........
Test script errors:
Timed out (2000ms) - Before 
      at tryOnTimeout (timers.js:224:11)
      at Timer.listOnTimeout (timers.js:198:5)
There were 1 test script error(s).
10 tests complete
Test duration: 2006 ms
```

I already configured and ran our project with travis-ci and snyk, it is working as shown in travis logs below.

```sh
travis_time:end:06b8dccc:start=1507905683228777800,finish=1507905723348587406,duration=40119809606
[0Ktravis_fold:end:install.1
[0Ktravis_fold:start:install.2
[0Ktravis_time:start:175a986c
[0K$ snyk protect
Successfully applied Snyk patches


travis_time:end:175a986c:start=1507905723357827630,finish=1507905726346392043,duration=2988564413
[0Ktravis_fold:end:install.2
[0Ktravis_fold:start:install.3
[0Ktravis_time:start:1e77b77b
[0K$ snyk test
✓ Tested 164 dependencies for known vulnerabilities, no vulnerable paths found.
```

**Comment by jfroffice** [comment]
@thakkaryash94 thank you for your expertise.

I will ping you when I am ready.

**Comment by j1348** [comment]
ok, I am going to check this.

**Comment by thakkaryash94** [comment]
So did you check?

**Comment by j1348** [comment]
I had SNYK_TOKEN to Travis.

**Comment by thakkaryash94** [comment]
Add .snyk in project and add below script into .travis.yml.
```
install:
    - npm install
    - snyk protect
    - snyk test
after_success: snyk monitor
```
as written in their blog. You can also add project to Snyk [here](https://snyk.io/docs/github) for pull request integration.
